// generated by Neptune Namespaces v4.x.x
// file: ArtAppKitBoilerPlate/Components/Pages/index.js

(module.exports = require('./namespace'))

.addModules({
  FiveWhys: require('./FiveWhys'),
  Home:     require('./Home'),
  Settings: require('./Settings')
});