// generated by Neptune Namespaces v4.x.x
// file: ArtAppKitBoilerPlate/Components/Partials/index.js

(module.exports = require('./namespace'))

.addModules({
  ApiKeySettings: require('./ApiKeySettings')
});