// generated by Neptune Namespaces v4.x.x
// file: ChatGptDemo/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App: require('./App')
});
require('./Pages');
require('./Partials');