// generated by Neptune Namespaces v4.x.x
// file: ChatGptDemo/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'ChatGptDemo',
  (class ChatGptDemo extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');
require('./Models/namespace');