// generated by Neptune Namespaces v4.x.x
// file: ArtAppKitBoilerPlate/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  Conversation:   require('./Conversation'),
  OpenAiSettings: require('./OpenAiSettings')
});